"""
Django settings for areaparking project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vkycdut2t=c01f+su75#1d+87y)wn)(arx&^nu-^iw7dgl_izk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.99.100', 'localhost', '127.0.0.1', '*.e-business.co.jp']
APPEND_SLASH = True
NUMBER_GROUPING = 3
CORS_ORIGIN_WHITELIST = (
    'localhost:8000',
    '127.0.0.1:8000'
)
SESSION_COOKIE_AGE = 60 * 30

# Application definition

INSTALLED_APPS = [
    'material.theme.cyan',
    'material',
    'material.frontend',
    'material.admin',
    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'parkinglot.apps.ParkinglotConfig',
    'master.apps.MasterConfig',
    'contract.apps.ContractConfig',
    'whiteboard.apps.WhiteboardConfig',
    'turnover.apps.TurnoverConfig',
    'revolution.apps.RevolutionConfig',
    'rest_framework',
    'django_filters',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'areaparking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'material.frontend.context_processors.modules',
            ],
        },
    },
]

WSGI_APPLICATION = 'areaparking.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

if sys.platform == "win32":
    DATABASES = {
        'default': {
            'ENGINE': 'sql_server.pyodbc',
            'NAME': 'areaparking',
            'USER': 'sa',
            'PASSWORD': 'root',
            'HOST': r'EB097-PC\SQLEXPRESS',
            'PORT': '',
        },
        'fk5dtsql': {
            'ENGINE': 'sql_server.pyodbc',
            'NAME': 'fk5dtsql',
            'USER': 'sa',
            'PASSWORD': 'root',
            'HOST': r'EB097-PC\SQLEXPRESS',
            'PORT': '',
        },
        # 'default': {
        #     'ENGINE': 'django.db.backends.sqlite3',
        #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        # }
    }
elif sys.platform == "darwin":
    DATABASES = {
        'default': {
            'ENGINE': 'sql_server.pyodbc',
            'NAME': 'areaparking',
            'USER': 'sa',
            'PASSWORD': 'root@123',
            'HOST': r'localhost',
            'PORT': '1433',
            'OPTIONS': {
                'driver': 'FreeTDS',
                'host_is_server': True,
                'extra_params': 'TDS_VERSION=7.3',  # TDS 7.3 in freetds supports latest SQL Server 2008 types.
            },
        },
        'fk5dtsql': {
            'ENGINE': 'sql_server.pyodbc',
            'NAME': 'fk5dtsql',
            'USER': 'sa',
            'PASSWORD': 'root@123',
            'HOST': r'localhost',
            'PORT': '1433',
            'OPTIONS': {
                'driver': 'FreeTDS',
                'host_is_server': True,
                'extra_params': 'TDS_VERSION=7.3',  # TDS 7.3 in freetds supports latest SQL Server 2008 types.
            },
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

DATABASE_ROUTERS = ['areaparking.db_router.DbRouter']

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'PAGE_SIZE': 15
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
LOG_ROOT = os.path.join(BASE_DIR, "logs")

if not os.path.exists(LOG_ROOT):
    os.mkdir(LOG_ROOT)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': "[%(asctime)s] %(levelname)s [PROCESS:%(process)d] [%(module)s:%(lineno)s] %(message)s",
            'datefmt': "%Y/%m/%d %H:%M:%S"
        },
    },
    'handlers': {
        'batch': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'formatter': 'standard',
            'filename': os.path.join(LOG_ROOT, "batch.log"),
        },
        'area_parking': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'formatter': 'standard',
            'filename': os.path.join(LOG_ROOT, "area_parking.log"),
        },
    },
    'loggers': {
        'revolution.management.commands': {
            'handlers': ['batch'],
            'level': 'INFO',
            'propagate': True,
        },
        'area_parking': {
            'handlers': ['area_parking'],
            'level': 'INFO',
            'propagate': True,
        },
    }
}
