# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 07:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkinglot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('contract_date', models.DateField(verbose_name='\u5951\u7d04\u65e5')),
                ('start_date', models.DateField(verbose_name='\u5951\u7d04\u958b\u59cb\u65e5')),
                ('end_date', models.DateField(verbose_name='\u5951\u7d04\u7d42\u4e86\u65e5')),
                ('pay_date', models.DateField(blank=True, help_text='\u672a\u5165\u529b\u306e\u5834\u5408\u3001\u5951\u7d04\u671f\u9593\u306e\u958b\u59cb\u65e5\u304c\u8cc3\u6599\u767a\u751f\u65e5\u3068\u3057\u3066\u6271\u308f\u308c\u307e\u3059', null=True, verbose_name='\u8cc3\u6599\u767a\u751f\u65e5')),
            ],
            options={
                'ordering': ['contractor', 'start_date'],
                'db_table': 'ap_contract',
                'verbose_name': '\u5951\u7d04\u60c5\u5831',
                'verbose_name_plural': '\u5951\u7d04\u60c5\u5831\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('code', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{1,8}$')], verbose_name='\u5951\u7d04\u8005No.')),
                ('segment', models.CharField(choices=[('1', '\u500b\u4eba'), ('2', '\u6cd5\u4eba')], max_length=1, verbose_name='\u5951\u7d04\u8005\u5206\u985e')),
                ('name', models.CharField(max_length=15, verbose_name='\u540d\u524d')),
                ('kana', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u30ab\u30ca')),
                ('post_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='\u90f5\u4fbf\u756a\u53f7')),
                ('address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4f\u6240\uff11')),
                ('address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4f\u6240\uff12')),
                ('tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u96fb\u8a71\u756a\u53f7')),
                ('fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u30d5\u30a1\u30c3\u30af\u30b9')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
                ('personal_gender', models.CharField(blank=True, choices=[('1', '\u7537'), ('2', '\u5973')], max_length=1, null=True, verbose_name='\u6027\u5225')),
                ('personal_birthday', models.DateField(blank=True, null=True, verbose_name='\u751f\u5e74\u6708\u65e5')),
                ('corporate_business_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u696d\u7a2e\uff0f\u4e8b\u696d')),
                ('corporate_web_site', models.URLField(blank=True, null=True, verbose_name='\u30db\u30fc\u30e0\u30da\u30fc\u30b8')),
                ('corporate_president', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4ee3\u8868\u8005\u540d')),
                ('corporate_staff_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u62c5\u5f53\u8005\u540d')),
                ('corporate_staff_department', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u62c5\u5f53\u8005\u6240\u5c5e')),
                ('corporate_staff_position', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u62c5\u5f53\u8005\u5f79\u8077')),
                ('corporate_extension', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5185\u7dda\u756a\u53f7')),
                ('corporate_capital', models.IntegerField(blank=True, null=True, verbose_name='\u8cc7\u672c\u91d1')),
                ('corporate_turnover', models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u53ce\uff0f\u5e74\u5546')),
                ('workplace_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u52e4\u52d9\u5148\u540d\u79f0')),
                ('workplace_post_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='\u52e4\u52d9\u5148\u90f5\u4fbf\u756a\u53f7')),
                ('workplace_address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u52e4\u52d9\u5148\u4f4f\u6240\uff11')),
                ('workplace_address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u52e4\u52d9\u5148\u4f4f\u6240\uff12')),
                ('workplace_tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u52e4\u52d9\u5148\u96fb\u8a71\u756a\u53f7')),
                ('workplace_fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u52e4\u52d9\u5148\u30d5\u30a1\u30c3\u30af\u30b9')),
                ('contact_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u9023\u7d61\u5148\u540d\u79f0')),
                ('contact_kana', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u9023\u7d61\u5148\u30ab\u30ca')),
                ('contact_post_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='\u9023\u7d61\u5148\u90f5\u4fbf\u756a\u53f7')),
                ('contact_address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u9023\u7d61\u5148\u4f4f\u6240\uff11')),
                ('contact_address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u9023\u7d61\u5148\u4f4f\u6240\uff12')),
                ('contact_tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u9023\u7d61\u5148\u96fb\u8a71\u756a\u53f7')),
                ('contact_fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u9023\u7d61\u5148\u30d5\u30a1\u30c3\u30af\u30b9')),
                ('contact_relation', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u9023\u7d61\u5148\u3068\u306e\u9593\u67c4')),
                ('delivery_type', models.CharField(blank=True, choices=[('01', '\u57fa\u672c\u60c5\u5831\u306e\u4f4f\u6240'), ('02', '\u52e4\u52d9\u5148'), ('03', '\u9023\u7d61\u5148'), ('04', '\u4fdd\u8a3c\u4eba'), ('99', '\u305d\u306e\u4ed6')], max_length=2, null=True, verbose_name='\u66f8\u985e\u9001\u4ed8\u5148\u533a\u5206')),
                ('delivery_honorific', models.CharField(blank=True, choices=[('1', '\u69d8'), ('2', '\u5fa1\u4e2d')], max_length=1, null=True, verbose_name='\u5b9b\u540d\u656c\u79f0')),
                ('delivery_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u9001\u4ed8\u5148\u540d\u79f0')),
                ('delivery_kana', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u9001\u4ed8\u5148\u30ab\u30ca')),
                ('delivery_post_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='\u9001\u4ed8\u5148\u90f5\u4fbf\u756a\u53f7')),
                ('delivery_address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u9001\u4ed8\u5148\u4f4f\u6240\uff11')),
                ('delivery_address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u9001\u4ed8\u5148\u4f4f\u6240\uff12')),
                ('delivery_tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u9001\u4ed8\u5148\u96fb\u8a71\u756a\u53f7')),
                ('delivery_fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u9001\u4ed8\u5148\u30d5\u30a1\u30c3\u30af\u30b9')),
                ('guarantor_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u4fdd\u8a3c\u4eba\u540d\u79f0')),
                ('guarantor_kana', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u4fdd\u8a3c\u4eba\u30ab\u30ca')),
                ('guarantor_birthday', models.DateField(blank=True, null=True, verbose_name='\u4fdd\u8a3c\u4eba\u751f\u5e74\u6708\u65e5')),
                ('guarantor_post_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='\u4fdd\u8a3c\u4eba\u90f5\u4fbf\u756a\u53f7')),
                ('guarantor_address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4fdd\u8a3c\u4eba\u4f4f\u6240\uff11')),
                ('guarantor_address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4fdd\u8a3c\u4eba\u4f4f\u6240\uff12')),
                ('guarantor_tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u4fdd\u8a3c\u4eba\u96fb\u8a71\u756a\u53f7')),
                ('guarantor_fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u4fdd\u8a3c\u4eba\u30d5\u30a1\u30c3\u30af\u30b9')),
                ('guarantor_relation', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4fdd\u8a3c\u4eba\u3068\u306e\u9593\u67c4')),
                ('guarantor_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'ap_contractor',
                'verbose_name': '\u5951\u7d04\u8005',
                'verbose_name_plural': '\u5951\u7d04\u8005\u4e00\u89a7',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contractor', verbose_name='\u5951\u7d04\u8005'),
        ),
        migrations.AddField(
            model_name='contract',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='\u99d0\u8eca\u5834'),
        ),
        migrations.AddField(
            model_name='contract',
            name='parking_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingPosition', verbose_name='\u8eca\u5ba4\u756a\u53f7'),
        ),
    ]
