# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0002_auto_20171023_2135'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('contract_date', models.DateField(verbose_name='\u5951\u7d04\u65e5')),
                ('start_date', models.DateField(verbose_name='\u5951\u7d04\u958b\u59cb\u65e5')),
                ('end_date', models.DateField(verbose_name='\u5951\u7d04\u7d42\u4e86\u65e5')),
                ('pay_date', models.DateField(blank=True, help_text='\u672a\u5165\u529b\u306e\u5834\u5408\u3001\u5951\u7d04\u671f\u9593\u306e\u958b\u59cb\u65e5\u304c\u8cc3\u6599\u767a\u751f\u65e5\u3068\u3057\u3066\u6271\u308f\u308c\u307e\u3059', null=True, verbose_name='\u8cc3\u6599\u767a\u751f\u65e5')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contractor', verbose_name='\u5951\u7d04\u8005')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='\u99d0\u8eca\u5834')),
                ('parking_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingPosition', verbose_name='\u8eca\u5ba4\u756a\u53f7')),
            ],
            options={
                'ordering': ['contractor', 'start_date'],
                'db_table': 'ap_contract',
                'verbose_name': '\u5951\u7d04\u60c5\u5831',
                'verbose_name_plural': '\u5951\u7d04\u60c5\u5831\u4e00\u89a7',
            },
        ),
    ]
