# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20171027_1519'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Bank', verbose_name='\u632f\u8fbc\u5148\u53e3\u5ea7'),
        ),
    ]
