# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revolution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairooms',
            options={'managed': False, 'verbose_name': '\u8eca\u5ba4', 'verbose_name_plural': '\u8eca\u5ba4\u4e00\u89a7'},
        ),
        migrations.AlterModelOptions(
            name='bkmst',
            options={'managed': False, 'verbose_name': '\u99d0\u8eca\u5834', 'verbose_name_plural': '\u99d0\u8eca\u5834\u4e00\u89a7'},
        ),
    ]
