# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 10:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('bank_name', models.CharField(max_length=20, verbose_name='\u9280\u884c\u540d\u79f0')),
                ('branch_no', models.CharField(max_length=7, verbose_name='\u652f\u5e97\u756a\u53f7')),
                ('branch_name', models.CharField(max_length=20, verbose_name='\u652f\u5e97\u540d\u79f0')),
                ('account_type', models.CharField(choices=[('1', '\u666e\u901a\u9810\u91d1'), ('2', '\u5b9a\u671f\u9810\u91d1'), ('3', '\u7dcf\u5408\u53e3\u5ea7'), ('4', '\u5f53\u5ea7\u9810\u91d1'), ('5', '\u8caf\u84c4\u9810\u91d1'), ('6', '\u5927\u53e3\u5b9a\u671f\u9810\u91d1'), ('7', '\u7a4d\u7acb\u5b9a\u671f\u9810\u91d1')], max_length=1, verbose_name='\u9810\u91d1\u7a2e\u985e')),
                ('account_number', models.CharField(max_length=7, verbose_name='\u53e3\u5ea7\u756a\u53f7')),
                ('account_holder', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u53e3\u5ea7\u540d\u7fa9')),
            ],
            options={
                'ordering': ['bank_name', 'branch_no'],
                'verbose_name_plural': '\u9280\u884c\u53e3\u5ea7\u4e00\u89a7',
                'db_table': 'mst_bank',
                'verbose_name': '\u9280\u884c\u53e3\u5ea7',
            },
        ),
        migrations.CreateModel(
            name='BankCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('code', models.CharField(max_length=4, verbose_name='\u91d1\u878d\u6a5f\u95a2\u30b3\u30fc\u30c9')),
                ('name', models.CharField(max_length=30, verbose_name='\u91d1\u878d\u6a5f\u95a2\u540d\u79f0')),
                ('kana', models.CharField(max_length=30, verbose_name='\u91d1\u878d\u6a5f\u95a2\u30ab\u30ca')),
            ],
            options={
                'ordering': ['code'],
                'db_table': 'mst_bank_code',
                'verbose_name': '\u91d1\u878d\u6a5f\u95a2',
                'verbose_name_plural': '\u91d1\u878d\u6a5f\u95a2\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='CarMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u30e1\u30fc\u30ab\u30fc')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'mst_car_maker',
                'verbose_name': '\u30e1\u30fc\u30ab\u30fc',
                'verbose_name_plural': '\u30e1\u30fc\u30ab\u30fc\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('name', models.CharField(max_length=50, verbose_name='\u8eca\u7a2e')),
                ('grade_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u30b0\u30ec\u30fc\u30c9\u540d')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='\u767a\u58f2\u5e74\u5ea6')),
                ('length', models.IntegerField(null=True, verbose_name='\u5168\u9577')),
                ('width', models.IntegerField(null=True, verbose_name='\u5168\u5e45')),
                ('height', models.IntegerField(null=True, verbose_name='\u5168\u9ad8')),
                ('weight', models.IntegerField(null=True, verbose_name='\u91cd\u91cf')),
                ('f_value', models.IntegerField(null=True, verbose_name='F\u5024')),
                ('r_value', models.IntegerField(null=True, verbose_name='R\u5024')),
                ('min_height', models.IntegerField(null=True, verbose_name='\uff92\uff70\uff76\uff70\u306e\u5730\u4e0a\u6700\u4f4e\u9ad8')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.CarMaker', verbose_name='\u30e1\u30fc\u30ab\u30fc')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': '\u8eca\u7a2e\u4e00\u89a7',
                'db_table': 'mst_car_model',
                'verbose_name': '\u8eca\u7a2e',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u4f1a\u793e\u540d')),
                ('kana', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u30d5\u30ea\u30ab\u30ca')),
                ('president', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4ee3\u8868\u8005\u540d')),
                ('post_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='\u90f5\u4fbf\u756a\u53f7')),
                ('address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4f\u6240\uff11')),
                ('address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4f\u6240\uff12')),
                ('tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u96fb\u8a71\u756a\u53f7')),
                ('fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u30d5\u30a1\u30c3\u30af\u30b9')),
            ],
            options={
                'db_table': 'ap_company',
                'verbose_name': '\u81ea\u793e\u60c5\u5831',
                'verbose_name_plural': '\u81ea\u793e\u60c5\u5831',
            },
        ),
        migrations.CreateModel(
            name='ManagementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('code', models.CharField(max_length=4, verbose_name='\u7ba1\u7406\u5f62\u614b\u30b3\u30fc\u30c9')),
                ('name', models.CharField(max_length=30, verbose_name='\u7ba1\u7406\u5f62\u614b\u540d\u79f0')),
            ],
            options={
                'ordering': ['code'],
                'db_table': 'mst_management_type',
                'verbose_name': '\u7ba1\u7406\u5f62\u614b',
                'verbose_name_plural': '\u7ba1\u7406\u5f62\u614b\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='ParkingLotType',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('code', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^\\d{1,4}$')], verbose_name='\u99d0\u8eca\u5834\u5206\u985eNo.')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u79f0')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
            ],
            options={
                'ordering': ['code'],
                'db_table': 'mst_parking_lot_type',
                'verbose_name': '\u99d0\u8eca\u5834\u5206\u985e',
                'verbose_name_plural': '\u99d0\u8eca\u5834\u5206\u985e\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='ParkingTimeLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u79f0')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'mst_parking_time_limit',
                'verbose_name': '\u6642\u9593\u5236\u9650',
                'verbose_name_plural': '\u6642\u9593\u5236\u9650\u4e00\u89a7',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together=set([('branch_no', 'account_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set([('maker', 'name', 'grade_name')]),
        ),
    ]
