# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 08:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('code', models.CharField(max_length=4, verbose_name='\u91d1\u878d\u6a5f\u95a2\u30b3\u30fc\u30c9')),
                ('name', models.CharField(max_length=30, verbose_name='\u91d1\u878d\u6a5f\u95a2\u540d\u79f0')),
                ('kana', models.CharField(max_length=30, verbose_name='\u91d1\u878d\u6a5f\u95a2\u30ab\u30ca')),
            ],
            options={
                'ordering': ['code'],
                'db_table': 'mst_bank_code',
                'verbose_name': '\u91d1\u878d\u6a5f\u95a2',
                'verbose_name_plural': '\u91d1\u878d\u6a5f\u95a2\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u4f1a\u793e\u540d')),
                ('kana', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u30d5\u30ea\u30ab\u30ca')),
                ('president', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4ee3\u8868\u8005\u540d')),
                ('post_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='\u90f5\u4fbf\u756a\u53f7')),
                ('address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4f\u6240\uff11')),
                ('address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4f\u6240\uff12')),
                ('tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u96fb\u8a71\u756a\u53f7')),
                ('fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u30d5\u30a1\u30c3\u30af\u30b9')),
            ],
            options={
                'db_table': 'ap_company',
                'verbose_name': '\u81ea\u793e\u60c5\u5831',
                'verbose_name_plural': '\u81ea\u793e\u60c5\u5831',
            },
        ),
        migrations.CreateModel(
            name='ParkingLotType',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('code', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^\\d{1,4}$')], verbose_name='\u99d0\u8eca\u5834\u5206\u985eNo.')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u79f0')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
            ],
            options={
                'ordering': ['code'],
                'db_table': 'mst_parking_lot_type',
                'verbose_name': '\u99d0\u8eca\u5834\u5206\u985e',
                'verbose_name_plural': '\u99d0\u8eca\u5834\u5206\u985e\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='ParkingTimeLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u79f0')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'mst_parking_time_limit',
                'verbose_name': '\u6642\u9593\u5236\u9650',
                'verbose_name_plural': '\u6642\u9593\u5236\u9650\u4e00\u89a7',
            },
        ),
    ]
