# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('code', models.CharField(max_length=4, verbose_name='\u7ba1\u7406\u5f62\u614b\u30b3\u30fc\u30c9')),
                ('name', models.CharField(max_length=30, verbose_name='\u7ba1\u7406\u5f62\u614b\u540d\u79f0')),
            ],
            options={
                'ordering': ['code'],
                'db_table': 'mst_management_type',
                'verbose_name': '\u7ba1\u7406\u5f62\u614b',
                'verbose_name_plural': '\u7ba1\u7406\u5f62\u614b\u4e00\u89a7',
            },
        ),
    ]
