# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('name', models.CharField(max_length=30, verbose_name='\u30e1\u30fc\u30ab\u30fc')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'mst_car_maker',
                'verbose_name': '\u30e1\u30fc\u30ab\u30fc',
                'verbose_name_plural': '\u30e1\u30fc\u30ab\u30fc\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('name', models.CharField(max_length=50, verbose_name='\u8eca\u7a2e')),
                ('sale_year', models.CharField(max_length=4, verbose_name='\u767a\u58f2\u5e74\u5ea6')),
                ('length', models.IntegerField(null=True, verbose_name='\u5168\u9577')),
                ('width', models.IntegerField(null=True, verbose_name='\u5168\u5e45')),
                ('height', models.IntegerField(null=True, verbose_name='\u5168\u9ad8')),
                ('weight', models.IntegerField(null=True, verbose_name='\u91cd\u91cf')),
                ('f_value', models.IntegerField(null=True, verbose_name='F\u5024')),
                ('r_value', models.IntegerField(null=True, verbose_name='R\u5024')),
                ('min_height', models.IntegerField(null=True, verbose_name='\uff92\uff70\uff76\uff70\u306e\u5730\u4e0a\u6700\u4f4e\u9ad8')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.CarMaker', verbose_name='\u30e1\u30fc\u30ab\u30fc')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'mst_car_model',
                'verbose_name': '\u30e1\u30fc\u30ab\u30fc',
                'verbose_name_plural': '\u30e1\u30fc\u30ab\u30fc\u4e00\u89a7',
            },
        ),
    ]
