# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_carmaker_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('bank_name', models.CharField(max_length=20, verbose_name='\u9280\u884c\u540d\u79f0')),
                ('branch_no', models.CharField(max_length=7, verbose_name='\u652f\u5e97\u756a\u53f7')),
                ('branch_name', models.CharField(max_length=20, verbose_name='\u652f\u5e97\u540d\u79f0')),
                ('account_type', models.CharField(choices=[('1', '\u666e\u901a\u9810\u91d1'), ('2', '\u5b9a\u671f\u9810\u91d1'), ('3', '\u7dcf\u5408\u53e3\u5ea7'), ('4', '\u5f53\u5ea7\u9810\u91d1'), ('5', '\u8caf\u84c4\u9810\u91d1'), ('6', '\u5927\u53e3\u5b9a\u671f\u9810\u91d1'), ('7', '\u7a4d\u7acb\u5b9a\u671f\u9810\u91d1')], max_length=1, verbose_name='\u9810\u91d1\u7a2e\u985e')),
                ('account_number', models.CharField(max_length=7, verbose_name='\u53e3\u5ea7\u756a\u53f7')),
                ('account_holder', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u53e3\u5ea7\u540d\u7fa9')),
            ],
            options={
                'ordering': ['bank_name', 'branch_no'],
                'verbose_name_plural': '\u9280\u884c\u53e3\u5ea7\u4e00\u89a7',
                'db_table': 'mst_bank',
                'verbose_name': '\u9280\u884c\u53e3\u5ea7',
            },
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['name'], 'verbose_name': '\u8eca\u7a2e', 'verbose_name_plural': '\u8eca\u7a2e\u4e00\u89a7'},
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together=set([('branch_no', 'account_number')]),
        ),
    ]
