# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20171027_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='marker',
            new_name='maker',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='grade_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u30b0\u30ec\u30fc\u30c9\u540d'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u767a\u58f2\u5e74\u5ea6'),
        ),
        migrations.AlterField(
            model_name='carmaker',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u30e1\u30fc\u30ab\u30fc'),
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='sale_year',
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set([('maker', 'name', 'grade_name')]),
        ),
    ]
