# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 10:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parkinglot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managerment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('code', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{1,8}$')], verbose_name='\u7ba1\u7406\u4f1a\u793eNo.')),
                ('name', models.CharField(max_length=100, verbose_name='\u7ba1\u7406\u4f1a\u793e\u540d\u79f0')),
                ('kana', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7ba1\u7406\u4f1a\u793e\u30ab\u30ca')),
                ('post_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='\u90f5\u4fbf\u756a\u53f7')),
                ('address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4f\u6240\uff11')),
                ('address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4f\u6240\uff12')),
                ('tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u96fb\u8a71\u756a\u53f7')),
                ('fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u30d5\u30a1\u30c3\u30af\u30b9')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.ManagementType', verbose_name='\u99d0\u8eca\u5834\u5206\u985e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('code', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{1,8}$')], verbose_name='\u99d0\u8eca\u5834No.')),
                ('name', models.CharField(max_length=100, verbose_name='\u99d0\u8eca\u5834\u540d\u79f0')),
                ('kana', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u99d0\u8eca\u5834\u30ab\u30ca')),
                ('pref_code', models.CharField(max_length=2, verbose_name='\u90fd\u9053\u5e9c\u770c\u30b3\u30fc\u30c9')),
                ('pref_name', models.CharField(max_length=15, verbose_name='\u90fd\u9053\u5e9c\u770c\u540d\u79f0')),
                ('city_code', models.CharField(max_length=5, verbose_name='\u5e02\u533a\u753a\u6751\u30b3\u30fc\u30c9')),
                ('city_name', models.CharField(max_length=15, verbose_name='\u5e02\u533a\u753a\u6751\u540d\u79f0')),
                ('town_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u753a\u57df\u540d\u79f0')),
                ('aza_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4e01\u756a\u5730')),
                ('other_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u305d\u306e\u4ed6')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='\u7d4c\u5ea6')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='\u7def\u5ea6')),
                ('post_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='\u90f5\u4fbf\u756a\u53f7')),
                ('traffic', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4ea4\u901a')),
                ('nearest_station', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u6700\u5bc4\u99c5')),
                ('car_count', models.IntegerField(default=0, verbose_name='\u99d0\u8eca\u53f0\u6570')),
                ('bike_count', models.IntegerField(default=0, verbose_name='\u99d0\u8f2a\u53f0\u6570')),
                ('is_existed_contractor_allowed', models.BooleanField(default=False, verbose_name='\u65e2\u5951\u7d04\u8005')),
                ('is_new_contractor_allowed', models.BooleanField(default=False, verbose_name='\u65b0\u30c6\u30ca\u30f3\u30c8')),
                ('free_end_date', models.DateField(blank=True, null=True, verbose_name='\u30d5\u30ea\u30fc\u30ec\u30f3\u30c8\u7d42\u4e86\u65e5')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.ParkingLotType', verbose_name='\u99d0\u8eca\u5834\u5206\u985e')),
            ],
            options={
                'ordering': ['code'],
                'db_table': 'ap_parking_lot',
                'verbose_name': '\u99d0\u8eca\u5834',
                'verbose_name_plural': '\u99d0\u8eca\u5834\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='ParkingLotDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('document', models.FileField(upload_to=parkinglot.models.get_doc_path)),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='\u99d0\u8eca\u5834')),
            ],
            options={
                'db_table': 'ap_parking_lot_doc',
                'verbose_name': '\u99d0\u8eca\u5834\u66f8\u985e',
                'verbose_name_plural': '\u99d0\u8eca\u5834\u66f8\u985e\u4e00\u5f0f',
            },
        ),
        migrations.CreateModel(
            name='ParkingLotImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('image', models.ImageField(upload_to=parkinglot.models.get_image_path)),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='\u99d0\u8eca\u5834')),
            ],
            options={
                'db_table': 'ap_parking_lot_image',
                'verbose_name': '\u99d0\u8eca\u5834\u753b\u50cf',
                'verbose_name_plural': '\u99d0\u8eca\u5834\u753b\u50cf\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='ParkingLotStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('start_date', models.DateField(verbose_name='\u958b\u59cb\u65e5')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Member', verbose_name='\u62c5\u5f53\u8005')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='\u99d0\u8eca\u5834')),
            ],
            options={
                'ordering': ['parking_lot', 'member', 'start_date'],
                'db_table': 'ap_parking_lot_staff',
                'verbose_name': '\u99d0\u8eca\u5834\u62c5\u5f53\u8005',
                'verbose_name_plural': '\u99d0\u8eca\u5834\u62c5\u5f53\u8005\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='ParkingPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('name', models.CharField(max_length=30, verbose_name='\u8eca\u5ba4\u540d\u79f0')),
                ('price_recruitment', models.IntegerField(blank=True, null=True, verbose_name='\u52df\u96c6\u8cc3\u6599\uff08\u7a0e\u8fbc\uff09')),
                ('price_recruitment_no_tax', models.IntegerField(blank=True, null=True, verbose_name='\u52df\u96c6\u8cc3\u6599\uff08\u7a0e\u629c\uff09')),
                ('price_homepage', models.IntegerField(blank=True, null=True, verbose_name='\u30db\u30fc\u30e0\u30da\u30fc\u30b8\u4fa1\u683c\uff08\u7a0e\u8fbc\uff09')),
                ('price_homepage_no_tax', models.IntegerField(blank=True, null=True, verbose_name='\u30db\u30fc\u30e0\u30da\u30fc\u30b8\u4fa1\u683c\uff08\u7a0e\u5225\uff09')),
                ('price_handbill', models.IntegerField(blank=True, null=True, verbose_name='\u30c1\u30e9\u30b7\u4fa1\u683c\uff08\u7a0e\u8fbc\uff09')),
                ('price_handbill_no_tax', models.IntegerField(blank=True, null=True, verbose_name='\u30c1\u30e9\u30b7\u4fa1\u683c\uff08\u7a0e\u5225\uff09')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='\u5168\u9577')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='\u5168\u5e45')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='\u5168\u9ad8')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='\u91cd\u91cf')),
                ('tyre_width', models.IntegerField(blank=True, null=True, verbose_name='\uff92\uff70\uff76\uff70\u306e\u30bf\u30a4\u30e4\u5e45')),
                ('tyre_width_ap', models.IntegerField(blank=True, null=True, verbose_name='AP\u8a08\u6e2c\u306e\u30bf\u30a4\u30e4\u5e45')),
                ('min_height', models.IntegerField(blank=True, null=True, verbose_name='\uff92\uff70\uff76\uff70\u306e\u5730\u4e0a\u6700\u4f4e\u9ad8')),
                ('min_height_ap', models.IntegerField(blank=True, null=True, verbose_name='AP\u8a08\u6e2c\u306e\u5730\u4e0a\u6700\u4f4e\u9ad8')),
                ('f_value', models.IntegerField(blank=True, null=True, verbose_name='F\u5024')),
                ('r_value', models.IntegerField(blank=True, null=True, verbose_name='R\u5024')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='\u99d0\u8eca\u5834')),
                ('time_limit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.ParkingTimeLimit', verbose_name='\u6642\u9593\u5236\u9650')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': '\u8eca\u5ba4\u4e00\u89a7',
                'db_table': 'ap_parking_position',
                'verbose_name': '\u8eca\u5ba4',
            },
        ),
        migrations.AlterUniqueTogether(
            name='parkingposition',
            unique_together=set([('parking_lot', 'name')]),
        ),
    ]
