# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 08:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('code', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{1,8}$')], verbose_name='\u99d0\u8eca\u5834No.')),
                ('name', models.CharField(max_length=100, verbose_name='\u99d0\u8eca\u5834\u540d\u79f0')),
                ('kana', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u99d0\u8eca\u5834\u30ab\u30ca')),
                ('pref_code', models.CharField(max_length=2, verbose_name='\u90fd\u9053\u5e9c\u770c\u30b3\u30fc\u30c9')),
                ('pref_name', models.CharField(max_length=15, verbose_name='\u90fd\u9053\u5e9c\u770c\u540d\u79f0')),
                ('city_code', models.CharField(max_length=5, verbose_name='\u5e02\u533a\u753a\u6751\u30b3\u30fc\u30c9')),
                ('city_name', models.CharField(max_length=15, verbose_name='\u5e02\u533a\u753a\u6751\u540d\u79f0')),
                ('town_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u753a\u57df\u540d\u79f0')),
                ('aza_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4e01\u756a\u5730')),
                ('other_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u305d\u306e\u4ed6')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='\u7d4c\u5ea6')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='\u7def\u5ea6')),
                ('post_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='\u90f5\u4fbf\u756a\u53f7')),
                ('traffic', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4ea4\u901a')),
                ('car_count', models.IntegerField(default=0, verbose_name='\u99d0\u8eca\u53f0\u6570')),
                ('bike_count', models.IntegerField(default=0, verbose_name='\u99d0\u8f2a\u53f0\u6570')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.ParkingLotType', verbose_name='\u99d0\u8eca\u5834\u5206\u985e')),
            ],
            options={
                'ordering': ['code'],
                'db_table': 'ap_parking_lot',
                'verbose_name': '\u99d0\u8eca\u5834',
                'verbose_name_plural': '\u99d0\u8eca\u5834\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='ParkingLotImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('image', models.ImageField(upload_to='images/parking')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
                ('parking_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='\u99d0\u8eca\u5834')),
            ],
            options={
                'db_table': 'ap_parking_lot_image',
                'verbose_name': '\u99d0\u8eca\u5834\u753b\u50cf',
                'verbose_name_plural': '\u99d0\u8eca\u5834\u753b\u50cf\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='ParkingPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('name', models.CharField(max_length=30, verbose_name='\u8eca\u5ba4\u540d\u79f0')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='\u5168\u9577')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='\u5168\u5e45')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='\u5168\u9ad8')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='\u91cd\u91cf')),
                ('tyre_width', models.IntegerField(blank=True, null=True, verbose_name='\uff92\uff70\uff76\uff70\u306e\u30bf\u30a4\u30e4\u5e45')),
                ('tyre_width_ap', models.IntegerField(blank=True, null=True, verbose_name='AP\u8a08\u6e2c\u306e\u30bf\u30a4\u30e4\u5e45')),
                ('min_height', models.IntegerField(blank=True, null=True, verbose_name='\uff92\uff70\uff76\uff70\u306e\u5730\u4e0a\u6700\u4f4e\u9ad8')),
                ('min_height_ap', models.IntegerField(blank=True, null=True, verbose_name='AP\u8a08\u6e2c\u306e\u5730\u4e0a\u6700\u4f4e\u9ad8')),
                ('f_value', models.IntegerField(blank=True, null=True, verbose_name='F\u5024')),
                ('r_value', models.IntegerField(blank=True, null=True, verbose_name='R\u5024')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
                ('parking_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='\u99d0\u8eca\u5834')),
                ('time_limit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.ParkingTimeLimit', verbose_name='\u6642\u9593\u5236\u9650')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'ap_parking_position',
                'verbose_name': '\u8eca\u5ba4',
                'verbose_name_plural': '\u8eca\u5ba4\u4e00\u89a7',
            },
        ),
    ]
