# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('parkinglot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLotStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('start_date', models.DateField(verbose_name='\u958b\u59cb\u65e5')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Member', verbose_name='\u62c5\u5f53\u8005')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='\u99d0\u8eca\u5834')),
            ],
            options={
                'ordering': ['parking_lot', 'member', 'start_date'],
                'db_table': 'ap_parking_lot_staff',
                'verbose_name': '\u99d0\u8eca\u5834\u62c5\u5f53\u8005',
                'verbose_name_plural': '\u99d0\u8eca\u5834\u62c5\u5f53\u8005\u4e00\u89a7',
            },
        ),
    ]
