# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerment',
            name='segment',
        ),
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'verbose_name': '\u99d0\u8eca\u5834', 'verbose_name_plural': '\u99d0\u8eca\u5834\u4e00\u89a7'},
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='aza_name',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='bike_count',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='car_count',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='code',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='kana',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='nearest_station',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='pref_code',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='pref_name',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='town_name',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='traffic',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='bk_no',
            field=models.IntegerField(default=1, verbose_name='\u8cc3\u8cb8\u9769\u547d\u7269\u4ef6'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Managerment',
        ),
    ]
