# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 10:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_managementtype'),
        ('parkinglot', '0002_auto_20171023_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managerment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('code', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{1,8}$')], verbose_name='\u7ba1\u7406\u4f1a\u793eNo.')),
                ('name', models.CharField(max_length=100, verbose_name='\u7ba1\u7406\u4f1a\u793e\u540d\u79f0')),
                ('kana', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7ba1\u7406\u4f1a\u793e\u30ab\u30ca')),
                ('post_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='\u90f5\u4fbf\u756a\u53f7')),
                ('address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4f\u6240\uff11')),
                ('address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4f\u6240\uff12')),
                ('tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u96fb\u8a71\u756a\u53f7')),
                ('fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u30d5\u30a1\u30c3\u30af\u30b9')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5099\u8003')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.ManagementType', verbose_name='\u99d0\u8eca\u5834\u5206\u985e')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
