# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0002_parkinglotstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='existed_contractor',
            field=models.BooleanField(default=False, verbose_name='\u65e2\u5951\u7d04\u8005'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='nearest_station',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u6700\u5bc4\u99c5'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='new_contractor',
            field=models.BooleanField(default=False, verbose_name='\u65b0\u30c6\u30ca\u30f3\u30c8'),
        ),
    ]
