# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0002_auto_20171106_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'managed': False, 'verbose_name': '\u99d0\u8eca\u5834', 'verbose_name_plural': '\u99d0\u8eca\u5834\u4e00\u89a7'},
        ),
    ]
