# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0003_managerment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parkingposition',
            unique_together=set([('parking_plot', 'name')]),
        ),
    ]
