# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0003_auto_20171031_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinglot',
            old_name='existed_contractor',
            new_name='is_existed_contractor_allowed',
        ),
        migrations.RenameField(
            model_name='parkinglot',
            old_name='new_contractor',
            new_name='is_new_contractor_allowed',
        ),
    ]
