# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0003_auto_20171107_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglotstaff',
            name='member',
        ),
        migrations.RemoveField(
            model_name='parkinglotstaff',
            name='parking_lot',
        ),
        migrations.AddField(
            model_name='parkingposition',
            name='seq_no',
            field=models.IntegerField(default=1, verbose_name='\u5185\u90e8\u756a\u53f7'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='parkingposition',
            unique_together=set([('parking_lot', 'seq_no')]),
        ),
        migrations.DeleteModel(
            name='ParkingLotStaff',
        ),
    ]
