# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0004_auto_20171107_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglotimage',
            name='parking_lot',
        ),
        migrations.DeleteModel(
            name='ParkingLotImage',
        ),
    ]
