# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0005_auto_20171031_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingposition',
            name='price_handbill',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u30c1\u30e9\u30b7\u4fa1\u683c\uff08\u7a0e\u8fbc\uff09'),
        ),
        migrations.AlterField(
            model_name='parkingposition',
            name='price_handbill_no_tax',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u30c1\u30e9\u30b7\u4fa1\u683c\uff08\u7a0e\u5225\uff09'),
        ),
        migrations.AlterField(
            model_name='parkingposition',
            name='price_homepage',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u30db\u30fc\u30e0\u30da\u30fc\u30b8\u4fa1\u683c\uff08\u7a0e\u8fbc\uff09'),
        ),
        migrations.AlterField(
            model_name='parkingposition',
            name='price_homepage_no_tax',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u30db\u30fc\u30e0\u30da\u30fc\u30b8\u4fa1\u683c\uff08\u7a0e\u5225\uff09'),
        ),
        migrations.AlterField(
            model_name='parkingposition',
            name='price_recruitment',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u52df\u96c6\u8cc3\u6599\uff08\u7a0e\u8fbc\uff09'),
        ),
        migrations.AlterField(
            model_name='parkingposition',
            name='price_recruitment_no_tax',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u52df\u96c6\u8cc3\u6599\uff08\u7a0e\u629c\uff09'),
        ),
    ]
