# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0006_auto_20171031_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerment',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.ManagementType', verbose_name='\u99d0\u8eca\u5834\u5206\u985e'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.ParkingLotType', verbose_name='\u99d0\u8eca\u5834\u5206\u985e'),
        ),
        migrations.AlterField(
            model_name='parkinglotimage',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='\u99d0\u8eca\u5834'),
        ),
        migrations.AlterField(
            model_name='parkinglotstaff',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Member', verbose_name='\u62c5\u5f53\u8005'),
        ),
        migrations.AlterField(
            model_name='parkinglotstaff',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='\u99d0\u8eca\u5834'),
        ),
        migrations.AlterField(
            model_name='parkingposition',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='\u99d0\u8eca\u5834'),
        ),
        migrations.AlterField(
            model_name='parkingposition',
            name='time_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.ParkingTimeLimit', verbose_name='\u6642\u9593\u5236\u9650'),
        ),
    ]
