# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcontract',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u5951\u7d04\u65e5'),
        ),
        migrations.AlterField(
            model_name='tempcontract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.Contractor', verbose_name='\u5951\u7d04\u8005'),
        ),
        migrations.AlterField(
            model_name='tempcontract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u5951\u7d04\u7d42\u4e86\u65e5'),
        ),
        migrations.AlterField(
            model_name='tempcontract',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkinglot.ParkingLot', verbose_name='\u99d0\u8eca\u5834'),
        ),
        migrations.AlterField(
            model_name='tempcontract',
            name='parking_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkinglot.ParkingPosition', verbose_name='\u8eca\u5ba4\u756a\u53f7'),
        ),
        migrations.AlterField(
            model_name='tempcontract',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u5951\u7d04\u958b\u59cb\u65e5'),
        ),
    ]
