# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 06:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.admin.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMailLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='action time')),
                ('sender', models.EmailField(max_length=254, verbose_name='差出人')),
                ('recipient', models.CharField(max_length=1000, verbose_name='宛先')),
                ('cc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ＣＣ')),
                ('bcc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ＢＣＣ')),
                ('title', models.CharField(max_length=50, verbose_name='件名')),
                ('body', models.TextField(verbose_name='メール本文')),
                ('attachment', models.CharField(blank=True, max_length=255, null=True, verbose_name='添付ファイル名')),
            ],
            options={
                'verbose_name': 'メール送信履歴',
                'verbose_name_plural': 'メール送信履歴',
                'db_table': 'ap_email_log',
                'ordering': ['-action_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='action time')),
                ('object_id', models.TextField(blank=True, null=True, verbose_name='object id')),
                ('object_repr', models.CharField(max_length=200, verbose_name='object repr')),
                ('action_flag', models.PositiveSmallIntegerField(verbose_name='action flag')),
                ('change_message', models.TextField(blank=True, verbose_name='change message')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='content type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'log entry',
                'verbose_name_plural': 'log entries',
                'db_table': 'django_admin_log',
                'ordering': ('-action_time',),
            },
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
