# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u79f0')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'ap_department',
                'verbose_name': '\u90e8\u7f72',
                'verbose_name_plural': '\u90e8\u7f72\u4e00\u89a7',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u6642')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u524a\u9664\u5e74\u6708\u65e5')),
                ('first_name', models.CharField(max_length=30, verbose_name='\u59d3')),
                ('last_name', models.CharField(max_length=30, verbose_name='\u540d')),
                ('gender', models.CharField(blank=True, choices=[('1', '\u7537'), ('2', '\u5973')], max_length=1, null=True, verbose_name='\u6027\u5225')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u751f\u5e74\u6708\u65e5')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='\u5165\u793e\u5e74\u6708\u65e5')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u4f1a\u793e\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9')),
                ('post_code', models.CharField(blank=True, help_text='\u6570\u5024\u3060\u3051\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3001\u4f8b\uff1a1230034', max_length=7, null=True, verbose_name='\u90f5\u4fbf\u756a\u53f7')),
                ('address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4f\u6240\uff11')),
                ('address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f4f\u6240\uff12')),
                ('phone', models.CharField(blank=True, help_text='\u6570\u5024\u3060\u3051\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3001\u4f8b\uff1a08012345678', max_length=11, null=True, verbose_name='\u96fb\u8a71\u756a\u53f7')),
                ('marriage', models.CharField(blank=True, choices=[('0', '\u672a\u5a5a'), ('1', '\u65e2\u5a5a')], max_length=1, null=True, verbose_name='\u5a5a\u59fb\u72b6\u6cc1')),
                ('is_retired', models.BooleanField(default=False, verbose_name='\u9000\u8077')),
                ('retired_date', models.DateField(blank=True, null=True, verbose_name='\u9000\u8077\u5e74\u6708\u65e5')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'db_table': 'ap_member',
                'verbose_name': '\u793e\u54e1',
                'verbose_name_plural': '\u793e\u54e1\u4e00\u89a7',
            },
        ),
    ]
